import { logoWallHeight } from "@/features/widgets/logo-motion";
import { testimonialHeight } from "@/features/testimonials/testimonial-height";
import type { WidgetDefinition } from "@/features/widgets/catalog-types";

export const WIDGET_CATALOG: WidgetDefinition[] = [
  {
    id: "footer-strip",
    name: "Footer strip",
    description:
      "One-line enterprise footer — Verified mark, partner logos, confirmed count.",
    section: "placement",
    placement: "footer",
    recommended: true,
    height: 48,
    requirementHint: "Works with Verified alone; logos appear when confirmed.",
  },
  {
    id: "partners-rotate",
    name: "Partners rotate",
    description:
      "Editorial logo field — mutually confirmed partners for trust sections.",
    section: "placement",
    placement: "partners",
    pro: true,
    height: logoWallHeight("swap-random", "md") - 12,
    requirementHint: "Requires at least one confirmed partner or client.",
    unavailableCtaHref: "/dashboard/partners",
    unavailableCtaLabel: "Confirm partners",
  },
  {
    id: "case-gallery",
    name: "Case gallery",
    description:
      "Dossier list of client-confirmed case studies for your Work page.",
    section: "placement",
    placement: "cases",
    pro: true,
    height: 340,
    requirementHint: "Requires at least one client-confirmed case study.",
    unavailableCtaHref: "/dashboard/cases",
    unavailableCtaLabel: "Open cases",
  },
  {
    id: "testimonials",
    name: "Testimonials",
    description:
      "Client-written words — curated from the studio, auto-updates when new ones publish.",
    section: "proof",
    pro: true,
    height: testimonialHeight("grid", 3),
    requirementHint: "Requires at least one published client testimonial.",
    unavailableCtaHref: "/dashboard/testimonials",
    unavailableCtaLabel: "Invite clients",
  },
  {
    id: "verified",
    name: "Verified",
    description: "Minimal Hansala Verified lockup for footers.",
    section: "essential",
    recommended: true,
    height: 44,
  },
  {
    id: "micro",
    name: "Micro",
    description: "Status word, proof strip, and Hansala seal — no logos.",
    section: "essential",
    height: 52,
  },
  {
    id: "horizontal",
    name: "Horizontal",
    description: "Full-width trust bar with level, proof strip, and count.",
    section: "essential",
    height: 56,
  },
  {
    id: "starter",
    name: "Starter",
    description: "Dark premium bar — Trustpilot-style, no partner logos.",
    section: "proof",
    pro: true,
    height: 120,
  },
  {
    id: "score",
    name: "TrustScore",
    description: "Large confirmed count with proof strip and level.",
    section: "proof",
    pro: true,
    height: 88,
  },
  {
    id: "trust-card",
    name: "Trust card",
    description: "Hansala Level with partners, clients, and projects.",
    section: "proof",
    pro: true,
    height: 132,
  },
  {
    id: "credentials",
    name: "Credentials",
    description: "Compact partners · clients · projects strip.",
    section: "proof",
    pro: true,
    height: 76,
  },
  {
    id: "references",
    name: "References",
    description: "Confirmed client list — initials only, never logos.",
    section: "proof",
    pro: true,
    height: 160,
    requirementHint: "Requires at least one confirmed client reference.",
    unavailableCtaHref: "/dashboard/partners",
    unavailableCtaLabel: "Confirm clients",
  },
  {
    id: "assessment",
    name: "Client assessment",
    description: "Would-work-again score and strengths.",
    section: "proof",
    pro: true,
    height: 120,
    requirementHint: "Requires ≥3 client answers",
    unavailableCtaHref: "/dashboard",
    unavailableCtaLabel: "Invite clients",
  },
  {
    id: "signature",
    name: "Signature seal",
    description: "Centered premium seal with level and count.",
    section: "signature",
    pro: true,
    height: 160,
  },
  {
    id: "logo-wall",
    name: "Logo wall",
    description:
      "Hansala Verified lockup above partner logos — curated from the studio.",
    section: "proof",
    placement: "partners",
    pro: true,
    height: logoWallHeight("grid", "md"),
    requirementHint: "Requires at least one confirmed partner or client.",
    unavailableCtaHref: "/dashboard/partners",
    unavailableCtaLabel: "Confirm partners",
  },
  {
    id: "case-stamp",
    name: "Case confirmation stamp",
    description:
      "Small strip for your case page — only renders when the client confirmed.",
    section: "proof",
    placement: "cases",
    height: 72,
    caseScoped: true,
    requirementHint: "Requires a client-confirmed case study.",
    unavailableCtaHref: "/dashboard/cases",
    unavailableCtaLabel: "Open cases",
  },
];
