/** Aliases for health, care, media, resources (DE / SR / EN). */
export const CATEGORY_ALIASES_EXTRA_C: Record<string, string> = {
  zahnarzt: "dental",
  dentist: "dental",
  dental: "dental",
  physiotherapie: "physiotherapy",
  physiotherapy: "physiotherapy",
  augenoptik: "optometry",
  optician: "optometry",
  psychologie: "mental-health",
  "mental health": "mental-health",
  pflegedienst: "home-care",
  "home care": "home-care",
  seniorenheim: "elderly-care",
  "elderly care": "elderly-care",
  zahntechnik: "dental-laboratories",
  biotechnologie: "biotech",
  biotech: "biotech",
  "klinische forschung": "clinical-research",
  friseur: "beauty-salons",
  salon: "beauty-salons",
  barber: "barber-shops",
  friseursalon: "barber-shops",
  wellness: "spa-wellness",
  spa: "spa-wellness",
  kosmetik: "cosmetics",
  fitness: "fitness-gyms",
  gym: "fitness-gyms",
  kita: "childcare",
  daycare: "childcare",
  "privat schule": "private-schools",
  nachhilfe: "tutoring",
  fahrschule: "driving-schools",
  "driving school": "driving-schools",
  sprachschule: "language-schools",
  universitat: "universities",
  university: "universities",
  firmenschulung: "corporate-training",
  film: "film-production",
  musikproduktion: "music-production",
  videospiele: "gaming",
  fernsehen: "broadcasting",
  verlag: "publishing",
  publisher: "publishing",
  bergbau: "mining",
  mining: "mining",
  "ol und gas": "oil-gas",
  "oil and gas": "oil-gas",
  versorgungsunternehmen: "utilities",
  utilities: "utilities",
  "chemische reinigung": "dry-cleaning",
  schneiderei: "tailoring",
  wascherei: "laundry-services",
  laundry: "laundry-services",
  tierarztpraxis: "pet-services",
  "pet care": "pet-services",
  bestattung: "funeral-services",
  funeral: "funeral-services",
  sozialdienst: "social-services",
  kirche: "religious-organizations",
  innenausbau: "interior-fitting",
  fensterreinigung: "window-cleaning",
  pool: "pool-services",
  zahlungsabwicklung: "payment-processing",
  inkasso: "debt-collection",
  aktuar: "actuarial",
  patent: "patent-services",
  einwanderung: "immigration-services",
  immigration: "immigration-services",
  telemarketing: "telemarketing",
  kundenservice: "customer-support",
  "customer support": "customer-support",
  dokumentenmanagement: "document-management",
  aktenverwaltung: "records-management",
  zeitarbeitsfirma: "staffing-temp",
  "temp staffing": "staffing-temp",
  headhunter: "executive-search",
  coaching: "coaching",
  eventtechnik: "event-technology",
  gastronomiebedarf: "catering-equipment",
  grosskuchen: "commercial-kitchen",
  sicherheitstechnik: "security-technology",
  brandmeldeanlage: "fire-alarm-systems",
  videoüberwachung: "cctv-surveillance",
  zutrittskontrolle: "access-control",
};
