/** Aliases for expanded taxonomy (DE / SR / EN). */
export const CATEGORY_ALIASES_EXTRA_B: Record<string, string> = {
  baustoff: "builders-merchants",
  "building materials": "builders-merchants",
  holzhandel: "timber-lumber",
  lumber: "timber-lumber",
  "hardware store": "hardware-supply",
  "industrial supply": "industrial-supply",
  burobedarf: "office-supplies",
  "office supplies": "office-supplies",
  beschilderung: "signage",
  messebau: "exhibition-stands",
  gartenbau: "landscaping-services",
  landscaping: "landscaping-services",
  gartencenter: "garden-centers",
  florist: "florists",
  cvrcar: "florists",
  "tree surgery": "tree-services",
  autowerkstatt: "automotive-repair",
  "car repair": "automotive-repair",
  autolackiererei: "car-body-shop",
  autovermietung: "car-rental",
  reifen: "tyre-services",
  tires: "tyre-services",
  autoteile: "auto-parts",
  flottenmanagement: "fleet-management",
  taxi: "taxi-transport",
  "private hire": "taxi-transport",
  busreisen: "bus-coach",
  luftfahrt: "aviation",
  "luft und raumfahrt": "aerospace",
  schiffahrt: "maritime-services",
  eisenbahn: "rail-transport",
  "online shop": "e-commerce",
  ecommerce: "e-commerce",
  mode: "fashion-apparel",
  fashion: "fashion-apparel",
  elektronikhandel: "electronics-retail",
  supermarket: "grocery-supermarket",
  grocery: "grocery-supermarket",
  baumarkt: "home-improvement-retail",
  mobelhandel: "furniture-retail",
  "furniture store": "furniture-retail",
  "school furniture": "furniture-manufacturing",
  backerei: "bakery-patisserie",
  bakery: "bakery-patisserie",
  brauerei: "brewery",
  weingut: "winery",
  lebensmittelgroshandel: "food-wholesale",
  "food wholesale": "food-wholesale",
  kaffee: "coffee-shops",
  coffee: "coffee-shops",
  metzgerei: "butchers",
  butcher: "butchers",
  import: "import-export",
  export: "import-export",
  rohstoffhandel: "commodity-trading",
  auktion: "auction-houses",
  coworking: "coworking",
  rechenzentrum: "data-centers",
  "data center": "data-centers",
  "it hardware": "it-hardware",
  spieleentwicklung: "game-development",
  "game development": "game-development",
  produktdesign: "product-design",
  "product design": "product-design",
  ux: "ux-design",
  "ux design": "ux-design",
  industriedesign: "industrial-design",
  "3d printing": "3d-printing",
  drohnen: "drone-services",
  drohne: "drone-services",
  "smart building": "smart-building",
  warmepumpe: "heat-pumps",
  "heat pump": "heat-pumps",
  batteriespeicher: "battery-storage",
  asbest: "asbestos-removal",
  umweltberatung: "environmental-consulting",
  prufung: "testing-inspection",
  kalibrierung: "calibration-services",
  marktforschung: "market-research",
  lohnabrechnung: "payroll-services",
  payroll: "payroll-services",
  "business process outsourcing": "outsourcing",
  dolmetschen: "interpretation",
};
