/** Lowercased alias → slug. Canonical names are indexed in match.ts. */
export const CATEGORY_ALIASES: Record<string, string> = {
  architekt: "architecture",
  architekturburo: "architecture",
  architektur: "architecture",
  arhitektura: "architecture",
  architect: "architecture",
  architects: "architecture",
  "architecture firm": "architecture",
  "architecture office": "architecture",
  innenarchitektur: "interior-design",
  "interior architecture": "interior-design",
  "unutrasnji dizajn": "interior-design",
  landschaftsarchitektur: "landscape-architecture",
  stadtebau: "urban-planning",
  urbanizam: "urban-planning",
  vermessung: "surveying",
  geodaesie: "surveying",
  ingenieur: "engineering",
  ingenieurburo: "engineering",
  inzenjering: "engineering",
  "inzenjerska firma": "engineering",
  tiefbau: "civil-engineering",
  hochbau: "construction",
  tragwerksplanung: "structural-engineering",
  tga: "mechanical-electrical",
  mep: "mechanical-electrical",
  bau: "construction",
  baufirma: "construction",
  bauunternehmen: "construction",
  graevina: "construction",
  gradevina: "construction",
  "construction company": "construction",
  contractor: "specialist-contractors",
  subcontractors: "specialist-contractors",
  "specialist contractor": "specialist-contractors",
  ausbau: "specialist-contractors",
  elektriker: "electrical-contractors",
  elektro: "electrical-contractors",
  sanitar: "plumbing-hvac",
  heizung: "plumbing-hvac",
  klima: "plumbing-hvac",
  dachdecker: "roofing",
  gerustbau: "scaffolding",
  stahlbau: "steel-fabrication",
  glaserei: "glazing",
  maler: "painting-finishing",
  bodenleger: "flooring",
  abbruch: "demolition",
  zimmerei: "carpentry",
  tischlerei: "carpentry",
  stolar: "carpentry",
  daemmung: "insulation",
  dammung: "insulation",
  brandschutz: "fire-protection",
  schlüsseldienst: "locksmiths",
  schluesseldienst: "locksmiths",
  bravar: "locksmiths",
  gebaudemanagement: "facility-management",
  "facility services": "facility-management",
  reinigung: "cleaning",
  gebaudereinigung: "cleaning",
  "cleaning company": "cleaning",
  ciscenje: "cleaning",
  "ciscenje objekata": "cleaning",
  sicherheit: "security-services",
  obezbedenje: "security-services",
  entsorgung: "waste-management",
  schaedlingsbekaempfung: "pest-control",
  "pest control": "pest-control",
  verpflegung: "catering",
  ketering: "catering",
  software: "software-development",
  "it - software": "software-development",
  "it-software": "software-development",
  softwareentwicklung: "software-development",
  programiranje: "software-development",
  "software company": "software-development",
  "mobile app-entwicklung": "software-development",
  "app-entwicklung": "software-development",
  "app entwicklung": "software-development",
  "mobile app development": "software-development",
  "mobile apps": "software-development",
  edv: "it-services",
  it: "it-services",
  "it dienstleister": "it-services",
  "it services": "it-services",
  agentur: "digital-agencies",
  "digital agency": "digital-agencies",
  werbeagentur: "advertising",
  anzeige: "advertising",
  werbung: "advertising",
  oglasavanje: "advertising",
  studio: "design-studios",
  "design studio": "design-studios",
  marketingagentur: "marketing",
  "online marketing": "marketing",
  pr: "media",
  presse: "media",
  beratung: "consulting",
  unternehmensberatung: "consulting",
  konsultant: "consulting",
  "management consulting": "consulting",
  rechtsanwalt: "legal",
  anwalt: "legal",
  advokat: "legal",
  notar: "notaries",
  notarski: "notaries",
  steuerberatung: "accounting",
  buchhaltung: "accounting",
  racunovodstvo: "accounting",
  versicherung: "insurance",
  osiguranje: "insurance",
  finanzdienstleistung: "financial-services",
  personalberatung: "recruitment",
  recruiting: "recruitment",
  zeitarbeit: "recruitment",
  staffing: "recruitment",
  weiterbildung: "education-training",
  schulung: "education-training",
  obuka: "education-training",
  uebersetzung: "translation",
  prevođenje: "translation",
  prevodjenje: "translation",
  spedicion: "logistics",
  spedicija: "logistics",
  logistik: "logistics",
  spediteur: "freight",
  reederei: "shipping",
  schifffahrt: "shipping",
  grosshandel: "wholesale",
  veleprodaja: "wholesale",
  produktion: "manufacturing",
  proizvodnja: "manufacturing",
  "school furniture": "manufacturing",
  furniture: "manufacturing",
  maschinenbau: "machinery",
  elektronik: "electronics",
  automobil: "automotive",
  kfz: "automotive",
  lebensmittel: "food-production",
  chemie: "chemicals",
  pharma: "pharmaceuticals",
  verpackung: "packaging",
  textil: "textiles",
  immobilien: "real-estate",
  nekretnine: "real-estate",
  projektentwicklung: "property-development",
  "real estate development": "property-development",
  energie: "energy",
  umweltschutz: "environmental-services",
  telekom: "telecommunications",
  gesundheit: "healthcare",
  zdravstvo: "healthcare",
  labor: "research-laboratories",
  laboratori: "research-laboratories",
  agriculture: "agriculture",
  landwirtschaft: "agriculture",
  poljoprivreda: "agriculture",
  farming: "agriculture",
  agrar: "agriculture",
  "call centre": "call-center",
  "call center": "call-center",
  "call-center": "call-center",
  "call-centre": "call-center",
  "call centre and bpo": "call-center",
  callcenter: "call-center",
  "kontakt center": "call-center",
  "contact center": "call-center",
  "contact centre": "call-center",
  bpo: "call-center",
  hotel: "hospitality",
  gastronomie: "hospitality",
  ugostiteljstvo: "hospitality",
  veranstaltung: "events",
  eventagentur: "events",
  reisen: "travel",
  turizam: "travel",
  fotografie: "photography-video",
  video: "photography-video",
  druckerei: "printing",
  stamparija: "printing",
};
