/** Extra aliases for additive categories (DE / SR / EN). */
export const CATEGORY_ALIASES_EXTRA: Record<string, string> = {
  "quantity surveyor": "quantity-surveying",
  baukostenplanung: "quantity-surveying",
  denkmalschutz: "heritage-conservation",
  bim: "bim-services",
  geotechnik: "geotechnical-engineering",
  akustik: "acoustic-engineering",
  verkehrsplanung: "traffic-engineering",
  wasserbau: "water-engineering",
  brandschutzplanung: "fire-engineering",
  generalunternehmer: "general-contracting",
  "general contractor": "general-contracting",
  fassade: "facade-systems",
  trockenbau: "drywall-plaster",
  maurer: "masonry",
  zidanje: "masonry",
  betonbau: "concrete-works",
  erdbau: "excavation-earthworks",
  aufzug: "elevators-lifts",
  liftovi: "elevators-lifts",
  photovoltaik: "solar-installation",
  "solar installation": "solar-installation",
  industriereinigung: "industrial-cleaning",
  gartenpflege: "grounds-maintenance",
  parkplatz: "parking-services",
  "web development": "web-development",
  webentwicklung: "web-development",
  "mobile apps": "mobile-apps",
  cybersicherheit: "cybersecurity",
  "it security": "cybersecurity",
  cloud: "cloud-services",
  "data analytics": "data-analytics",
  datenanalyse: "data-analytics",
  "machine learning": "ai-machine-learning",
  ki: "ai-machine-learning",
  erp: "erp-systems",
  markenberatung: "branding",
  branding: "branding",
  "public relations": "public-relations",
  "content marketing": "content-marketing",
  seo: "seo-sem",
  sem: "seo-sem",
  "packaging design": "packaging-design",
  "management consulting": "management-consulting",
  steuerberatung: "tax-advisory",
  wirtschaftsprufung: "audit",
  audit: "audit",
  "hr consulting": "hr-consulting",
  "hr beratung": "hr-consulting",
  compliance: "compliance",
  bank: "banking",
  banking: "banking",
  fintech: "fintech",
  makler: "brokerage",
  brokerage: "brokerage",
  lagerhaltung: "warehousing",
  skladiste: "warehousing",
  kurier: "courier-express",
  zoll: "customs-brokerage",
  einzelhandel: "retail",
  maloprodaja: "retail",
  metallbau: "metalworking",
  kunststoff: "plastics",
  mobel: "furniture-manufacturing",
  "property management": "property-management",
  hausverwaltung: "property-management",
  immobilienmakler: "property-brokerage",
  erneuerbare: "renewable-energy",
  recycling: "recycling",
  wasseraufbereitung: "water-treatment",
  medizintechnik: "medical-devices",
  veterinar: "veterinary",
  apotheke: "pharmacies",
  restaurant: "restaurants",
  gastronomie: "restaurants",
  sport: "sports-leisure",
  "public administration": "public-administration",
  verwaltung: "public-administration",
  ngo: "ngo-associations",
  verein: "ngo-associations",
  udruzenje: "ngo-associations",
};
