import type { CategoryGroup } from "@/features/categories/group-types";

export const CATEGORY_GROUPS_A: CategoryGroup[] = [
  {
    id: "architecture-planning",
    name: "Architecture & planning",
    slugs: [
      "architecture",
      "interior-design",
      "landscape-architecture",
      "urban-planning",
      "surveying",
      "quantity-surveying",
      "heritage-conservation",
      "bim-services",
    ],
  },
  {
    id: "engineering",
    name: "Engineering",
    slugs: [
      "engineering",
      "civil-engineering",
      "structural-engineering",
      "mechanical-electrical",
      "geotechnical-engineering",
      "acoustic-engineering",
      "traffic-engineering",
      "water-engineering",
      "fire-engineering",
    ],
  },
  {
    id: "construction-trades",
    name: "Construction & trades",
    slugs: [
      "construction",
      "specialist-contractors",
      "general-contracting",
      "electrical-contractors",
      "plumbing-hvac",
      "roofing",
      "scaffolding",
      "steel-fabrication",
      "glazing",
      "facade-systems",
      "painting-finishing",
      "flooring",
      "drywall-plaster",
      "masonry",
      "concrete-works",
      "excavation-earthworks",
      "demolition",
      "carpentry",
      "insulation",
      "fire-protection",
      "elevators-lifts",
      "solar-installation",
      "locksmiths",
    ],
  },
  {
    id: "facility-services",
    name: "Facility & building services",
    slugs: [
      "facility-management",
      "cleaning",
      "industrial-cleaning",
      "security-services",
      "waste-management",
      "pest-control",
      "grounds-maintenance",
      "parking-services",
      "catering",
    ],
  },
  {
    id: "technology",
    name: "Technology & digital",
    slugs: [
      "software-development",
      "web-development",
      "mobile-apps",
      "it-services",
      "cybersecurity",
      "cloud-services",
      "data-analytics",
      "ai-machine-learning",
      "erp-systems",
      "digital-agencies",
      "telecommunications",
    ],
  },
  {
    id: "creative-marketing",
    name: "Creative & marketing",
    slugs: [
      "design-studios",
      "advertising",
      "marketing",
      "branding",
      "public-relations",
      "content-marketing",
      "seo-sem",
      "media",
      "photography-video",
      "printing",
      "packaging-design",
    ],
  },
];
