import type { CategoryGroup } from "@/features/categories/group-types";

export const CATEGORY_GROUPS_C: CategoryGroup[] = [
  {
    id: "building-supply",
    name: "Building supply & outdoor",
    slugs: [
      "builders-merchants",
      "timber-lumber",
      "hardware-supply",
      "industrial-supply",
      "office-supplies",
      "landscaping-services",
      "garden-centers",
      "florists",
      "tree-services",
      "signage",
      "exhibition-stands",
      "interior-fitting",
      "asbestos-removal",
    ],
  },
  {
    id: "automotive-transport",
    name: "Automotive & transport",
    slugs: [
      "automotive-repair",
      "car-body-shop",
      "car-rental",
      "tyre-services",
      "auto-parts",
      "fleet-management",
      "taxi-transport",
      "bus-coach",
      "aviation",
      "aerospace",
      "maritime-services",
      "rail-transport",
    ],
  },
  {
    id: "retail-commerce",
    name: "Retail & commerce",
    slugs: [
      "e-commerce",
      "fashion-apparel",
      "electronics-retail",
      "grocery-supermarket",
      "home-improvement-retail",
      "furniture-retail",
      "import-export",
      "commodity-trading",
      "auction-houses",
    ],
  },
  {
    id: "food-beverage",
    name: "Food & beverage",
    slugs: [
      "bakery-patisserie",
      "brewery",
      "winery",
      "food-wholesale",
      "food-distribution",
      "coffee-shops",
      "butchers",
      "catering-equipment",
      "commercial-kitchen",
    ],
  },
  {
    id: "health-care",
    name: "Health & care",
    slugs: [
      "dental",
      "physiotherapy",
      "optometry",
      "mental-health",
      "home-care",
      "elderly-care",
      "dental-laboratories",
      "biotech",
      "clinical-research",
      "social-services",
    ],
  },
  {
    id: "beauty-wellness",
    name: "Beauty, fitness & wellness",
    slugs: [
      "beauty-salons",
      "barber-shops",
      "spa-wellness",
      "cosmetics",
      "fitness-gyms",
    ],
  },
  {
    id: "education-childcare",
    name: "Education & childcare",
    slugs: [
      "childcare",
      "private-schools",
      "tutoring",
      "driving-schools",
      "language-schools",
      "universities",
      "corporate-training",
      "coaching",
    ],
  },
];
