import type { CategoryGroup } from "@/features/categories/group-types";

export const CATEGORY_GROUPS_D: CategoryGroup[] = [
  {
    id: "media-entertainment",
    name: "Media & entertainment",
    slugs: [
      "film-production",
      "music-production",
      "gaming",
      "game-development",
      "broadcasting",
      "publishing",
    ],
  },
  {
    id: "resources-utilities",
    name: "Resources & utilities",
    slugs: [
      "mining",
      "oil-gas",
      "utilities",
      "environmental-consulting",
      "smart-building",
      "heat-pumps",
      "battery-storage",
    ],
  },
  {
    id: "personal-services",
    name: "Personal & consumer services",
    slugs: [
      "dry-cleaning",
      "tailoring",
      "laundry-services",
      "pet-services",
      "funeral-services",
      "window-cleaning",
      "pool-services",
      "religious-organizations",
    ],
  },
  {
    id: "business-support",
    name: "Business support & ops",
    slugs: [
      "coworking",
      "data-centers",
      "it-hardware",
      "market-research",
      "payroll-services",
      "outsourcing",
      "telemarketing",
      "customer-support",
      "document-management",
      "records-management",
      "staffing-temp",
      "executive-search",
      "interpretation",
      "payment-processing",
      "debt-collection",
      "actuarial",
      "patent-services",
      "immigration-services",
      "political-consulting",
      "lobbying",
      "event-technology",
    ],
  },
  {
    id: "design-product",
    name: "Design & product",
    slugs: [
      "product-design",
      "ux-design",
      "industrial-design",
      "3d-printing",
      "drone-services",
    ],
  },
  {
    id: "security-systems",
    name: "Security systems",
    slugs: [
      "security-technology",
      "fire-alarm-systems",
      "cctv-surveillance",
      "access-control",
    ],
  },
  {
    id: "quality-labs",
    name: "Testing & calibration",
    slugs: ["testing-inspection", "calibration-services"],
  },
];
