import type { CategoryGroup } from "@/features/categories/group-types";

export const CATEGORY_GROUPS_B: CategoryGroup[] = [
  {
    id: "professional-services",
    name: "Professional services",
    slugs: [
      "consulting",
      "management-consulting",
      "legal",
      "notaries",
      "accounting",
      "tax-advisory",
      "audit",
      "hr-consulting",
      "recruitment",
      "education-training",
      "translation",
      "compliance",
    ],
  },
  {
    id: "finance",
    name: "Finance & insurance",
    slugs: [
      "financial-services",
      "insurance",
      "banking",
      "fintech",
      "brokerage",
    ],
  },
  {
    id: "logistics-trade",
    name: "Logistics & trade",
    slugs: [
      "logistics",
      "freight",
      "shipping",
      "warehousing",
      "courier-express",
      "customs-brokerage",
      "wholesale",
      "retail",
    ],
  },
  {
    id: "manufacturing",
    name: "Manufacturing & industry",
    slugs: [
      "manufacturing",
      "machinery",
      "electronics",
      "automotive",
      "metalworking",
      "plastics",
      "furniture-manufacturing",
      "food-production",
      "chemicals",
      "pharmaceuticals",
      "packaging",
      "textiles",
    ],
  },
  {
    id: "property-energy",
    name: "Property, energy & environment",
    slugs: [
      "real-estate",
      "property-development",
      "property-management",
      "property-brokerage",
      "energy",
      "renewable-energy",
      "environmental-services",
      "recycling",
      "water-treatment",
    ],
  },
  {
    id: "health-life",
    name: "Health & life sciences",
    slugs: [
      "healthcare",
      "medical-devices",
      "veterinary",
      "research-laboratories",
      "pharmacies",
    ],
  },
  {
    id: "hospitality-public",
    name: "Hospitality, public & other",
    slugs: [
      "hospitality",
      "restaurants",
      "events",
      "travel",
      "sports-leisure",
      "agriculture",
      "call-center",
      "public-administration",
      "ngo-associations",
    ],
  },
];
