/** Canonical ranking categories — English names, one primary slug each. */
export type CanonicalCategory = { slug: string; name: string };

export const CANONICAL_CATEGORIES: CanonicalCategory[] = [
  { slug: "architecture", name: "Architecture" },
  { slug: "interior-design", name: "Interior design" },
  { slug: "landscape-architecture", name: "Landscape architecture" },
  { slug: "urban-planning", name: "Urban planning" },
  { slug: "engineering", name: "Engineering" },
  { slug: "civil-engineering", name: "Civil engineering" },
  { slug: "structural-engineering", name: "Structural engineering" },
  { slug: "mechanical-electrical", name: "Mechanical and electrical" },
  { slug: "construction", name: "Construction" },
  { slug: "specialist-contractors", name: "Specialist contractors" },
  { slug: "electrical-contractors", name: "Electrical contractors" },
  { slug: "plumbing-hvac", name: "Plumbing and HVAC" },
  { slug: "roofing", name: "Roofing" },
  { slug: "scaffolding", name: "Scaffolding" },
  { slug: "steel-fabrication", name: "Steel fabrication" },
  { slug: "glazing", name: "Glazing" },
  { slug: "painting-finishing", name: "Painting and finishing" },
  { slug: "flooring", name: "Flooring" },
  { slug: "demolition", name: "Demolition" },
  { slug: "facility-management", name: "Facility management" },
  { slug: "cleaning", name: "Cleaning" },
  { slug: "security-services", name: "Security services" },
  { slug: "waste-management", name: "Waste management" },
  { slug: "software-development", name: "Software development" },
  { slug: "it-services", name: "IT services" },
  { slug: "digital-agencies", name: "Digital agencies" },
  { slug: "design-studios", name: "Design studios" },
  { slug: "advertising", name: "Advertising" },
  { slug: "consulting", name: "Consulting" },
  { slug: "legal", name: "Legal" },
  { slug: "accounting", name: "Accounting" },
  { slug: "logistics", name: "Logistics" },
  { slug: "freight", name: "Freight" },
  { slug: "manufacturing", name: "Manufacturing" },
  { slug: "real-estate", name: "Real estate" },
  { slug: "property-development", name: "Property development" },
  { slug: "energy", name: "Energy" },
  { slug: "telecommunications", name: "Telecommunications" },
  { slug: "healthcare", name: "Healthcare" },
  { slug: "hospitality", name: "Hospitality" },
];

/** Lowercased alias → slug. Names are added at runtime in match.ts. */
export const CATEGORY_ALIASES: Record<string, string> = {
  architekt: "architecture",
  architekturburo: "architecture",
  architektur: "architecture",
  arhitektura: "architecture",
  architect: "architecture",
  architects: "architecture",
  "architecture firm": "architecture",
  "architecture office": "architecture",
  innenarchitektur: "interior-design",
  "interior architecture": "interior-design",
  "unutrasnji dizajn": "interior-design",
  landschaftsarchitektur: "landscape-architecture",
  stadtebau: "urban-planning",
  "urbanizam": "urban-planning",
  ingenieur: "engineering",
  ingenieurburo: "engineering",
  inzenjering: "engineering",
  "inzenjerska firma": "engineering",
  tiefbau: "civil-engineering",
  hochbau: "construction",
  tragwerksplanung: "structural-engineering",
  tga: "mechanical-electrical",
  "mep": "mechanical-electrical",
  bau: "construction",
  baufirma: "construction",
  bauunternehmen: "construction",
  graevina: "construction",
  gradevina: "construction",
  "construction company": "construction",
  contractor: "specialist-contractors",
  subcontractors: "specialist-contractors",
  "specialist contractor": "specialist-contractors",
  ausbau: "specialist-contractors",
  elektriker: "electrical-contractors",
  elektro: "electrical-contractors",
  sanitar: "plumbing-hvac",
  heizung: "plumbing-hvac",
  klima: "plumbing-hvac",
  dachdecker: "roofing",
  gerustbau: "scaffolding",
  stahlbau: "steel-fabrication",
  glaserei: "glazing",
  maler: "painting-finishing",
  bodenleger: "flooring",
  abbruch: "demolition",
  gebaudemanagement: "facility-management",
  "facility services": "facility-management",
  reinigung: "cleaning",
  gebaudereinigung: "cleaning",
  "cleaning company": "cleaning",
  ciscenje: "cleaning",
  "ciscenje objekata": "cleaning",
  sicherheit: "security-services",
  obezbedenje: "security-services",
  entsorgung: "waste-management",
  software: "software-development",
  "it - software": "software-development",
  "it-software": "software-development",
  softwareentwicklung: "software-development",
  programiranje: "software-development",
  "software company": "software-development",
  edv: "it-services",
  "it dienstleister": "it-services",
  "it services": "it-services",
  agentur: "digital-agencies",
  "digital agency": "digital-agencies",
  werbeagentur: "advertising",
  studio: "design-studios",
  "design studio": "design-studios",
  beratung: "consulting",
  unternehmensberatung: "consulting",
  konsultant: "consulting",
  "management consulting": "consulting",
  rechtsanwalt: "legal",
  anwalt: "legal",
  advokat: "legal",
  steuerberatung: "accounting",
  buchhaltung: "accounting",
  racunovodstvo: "accounting",
  spedicion: "logistics",
  spedicija: "logistics",
  logistik: "logistics",
  spediteur: "freight",
  produktion: "manufacturing",
  proizvodnja: "manufacturing",
  immobilien: "real-estate",
  nekretnine: "real-estate",
  projektentwicklung: "property-development",
  "real estate development": "property-development",
  energie: "energy",
  telekom: "telecommunications",
  gesundheit: "healthcare",
  zdravstvo: "healthcare",
  hotel: "hospitality",
  gastronomie: "hospitality",
  ugostiteljstvo: "hospitality",
};
