import type { CanonicalCategory } from "@/features/categories/taxonomy-types";

/** Health, care, education, media, resources, personal services. */
export const TAXONOMY_EXTRA_C: CanonicalCategory[] = [
  { slug: "dental", name: "Dental" },
  { slug: "physiotherapy", name: "Physiotherapy" },
  { slug: "optometry", name: "Optometry" },
  { slug: "mental-health", name: "Mental health" },
  { slug: "home-care", name: "Home care" },
  { slug: "elderly-care", name: "Elderly care" },
  { slug: "dental-laboratories", name: "Dental laboratories" },
  { slug: "biotech", name: "Biotechnology" },
  { slug: "clinical-research", name: "Clinical research" },
  { slug: "beauty-salons", name: "Beauty salons" },
  { slug: "barber-shops", name: "Barber shops" },
  { slug: "spa-wellness", name: "Spa and wellness" },
  { slug: "cosmetics", name: "Cosmetics" },
  { slug: "fitness-gyms", name: "Fitness and gyms" },
  { slug: "childcare", name: "Childcare" },
  { slug: "private-schools", name: "Private schools" },
  { slug: "tutoring", name: "Tutoring" },
  { slug: "driving-schools", name: "Driving schools" },
  { slug: "language-schools", name: "Language schools" },
  { slug: "universities", name: "Universities and colleges" },
  { slug: "corporate-training", name: "Corporate training" },
  { slug: "film-production", name: "Film production" },
  { slug: "music-production", name: "Music production" },
  { slug: "gaming", name: "Gaming" },
  { slug: "broadcasting", name: "Broadcasting" },
  { slug: "publishing", name: "Publishing" },
  { slug: "mining", name: "Mining" },
  { slug: "oil-gas", name: "Oil and gas" },
  { slug: "utilities", name: "Utilities" },
  { slug: "dry-cleaning", name: "Dry cleaning" },
  { slug: "tailoring", name: "Tailoring" },
  { slug: "laundry-services", name: "Laundry services" },
  { slug: "pet-services", name: "Pet services" },
  { slug: "funeral-services", name: "Funeral services" },
  { slug: "social-services", name: "Social services" },
  { slug: "religious-organizations", name: "Religious organizations" },
  { slug: "interior-fitting", name: "Interior fitting" },
  { slug: "window-cleaning", name: "Window cleaning" },
  { slug: "pool-services", name: "Pool services" },
  { slug: "payment-processing", name: "Payment processing" },
  { slug: "debt-collection", name: "Debt collection" },
  { slug: "actuarial", name: "Actuarial services" },
  { slug: "patent-services", name: "Patent services" },
  { slug: "immigration-services", name: "Immigration services" },
  { slug: "political-consulting", name: "Political consulting" },
  { slug: "lobbying", name: "Lobbying" },
  { slug: "security-technology", name: "Security technology" },
  { slug: "fire-alarm-systems", name: "Fire alarm systems" },
  { slug: "cctv-surveillance", name: "CCTV and surveillance" },
  { slug: "access-control", name: "Access control" },
  { slug: "telemarketing", name: "Telemarketing" },
  { slug: "customer-support", name: "Customer support" },
  { slug: "document-management", name: "Document management" },
  { slug: "records-management", name: "Records management" },
  { slug: "staffing-temp", name: "Temporary staffing" },
  { slug: "executive-search", name: "Executive search" },
  { slug: "coaching", name: "Coaching" },
  { slug: "event-technology", name: "Event technology" },
  { slug: "catering-equipment", name: "Catering equipment" },
  { slug: "commercial-kitchen", name: "Commercial kitchen equipment" },
];
