import type { CanonicalCategory } from "@/features/categories/taxonomy-types";

/** Building supply, automotive, transport, retail, food. */
export const TAXONOMY_EXTRA_B: CanonicalCategory[] = [
  { slug: "builders-merchants", name: "Building materials supply" },
  { slug: "timber-lumber", name: "Timber and lumber" },
  { slug: "hardware-supply", name: "Hardware supply" },
  { slug: "industrial-supply", name: "Industrial supply" },
  { slug: "office-supplies", name: "Office supplies" },
  { slug: "signage", name: "Signage" },
  { slug: "exhibition-stands", name: "Exhibition stands" },
  { slug: "landscaping-services", name: "Landscaping services" },
  { slug: "garden-centers", name: "Garden centers" },
  { slug: "florists", name: "Florists" },
  { slug: "tree-services", name: "Tree surgery" },
  { slug: "automotive-repair", name: "Automotive repair" },
  { slug: "car-body-shop", name: "Car body shop" },
  { slug: "car-rental", name: "Car rental" },
  { slug: "tyre-services", name: "Tyre services" },
  { slug: "auto-parts", name: "Auto parts" },
  { slug: "fleet-management", name: "Fleet management" },
  { slug: "taxi-transport", name: "Taxi and private hire" },
  { slug: "bus-coach", name: "Bus and coach" },
  { slug: "aviation", name: "Aviation" },
  { slug: "aerospace", name: "Aerospace" },
  { slug: "maritime-services", name: "Maritime services" },
  { slug: "rail-transport", name: "Rail transport" },
  { slug: "e-commerce", name: "E-commerce" },
  { slug: "fashion-apparel", name: "Fashion and apparel" },
  { slug: "electronics-retail", name: "Electronics retail" },
  { slug: "grocery-supermarket", name: "Grocery and supermarkets" },
  { slug: "home-improvement-retail", name: "Home improvement retail" },
  { slug: "furniture-retail", name: "Furniture retail" },
  { slug: "bakery-patisserie", name: "Bakery and patisserie" },
  { slug: "brewery", name: "Brewery" },
  { slug: "winery", name: "Winery" },
  { slug: "food-wholesale", name: "Food wholesale" },
  { slug: "food-distribution", name: "Food distribution" },
  { slug: "coffee-shops", name: "Coffee shops" },
  { slug: "butchers", name: "Butchers" },
  { slug: "import-export", name: "Import and export" },
  { slug: "commodity-trading", name: "Commodity trading" },
  { slug: "auction-houses", name: "Auction houses" },
  { slug: "coworking", name: "Coworking" },
  { slug: "data-centers", name: "Data centers" },
  { slug: "it-hardware", name: "IT hardware" },
  { slug: "game-development", name: "Game development" },
  { slug: "product-design", name: "Product design" },
  { slug: "ux-design", name: "UX design" },
  { slug: "industrial-design", name: "Industrial design" },
  { slug: "3d-printing", name: "3D printing" },
  { slug: "drone-services", name: "Drone services" },
  { slug: "smart-building", name: "Smart building" },
  { slug: "heat-pumps", name: "Heat pumps" },
  { slug: "battery-storage", name: "Battery storage" },
  { slug: "asbestos-removal", name: "Asbestos removal" },
  { slug: "environmental-consulting", name: "Environmental consulting" },
  { slug: "testing-inspection", name: "Testing and inspection" },
  { slug: "calibration-services", name: "Calibration services" },
  { slug: "market-research", name: "Market research" },
  { slug: "payroll-services", name: "Payroll services" },
  { slug: "outsourcing", name: "Business process outsourcing" },
  { slug: "interpretation", name: "Interpretation" },
];
