import type { CanonicalCategory } from "@/features/categories/taxonomy-types";

/** Additive leaves — registration browse + ranking. */
export const TAXONOMY_EXTRA: CanonicalCategory[] = [
  { slug: "quantity-surveying", name: "Quantity surveying" },
  { slug: "heritage-conservation", name: "Heritage conservation" },
  { slug: "bim-services", name: "BIM services" },
  { slug: "geotechnical-engineering", name: "Geotechnical engineering" },
  { slug: "acoustic-engineering", name: "Acoustic engineering" },
  { slug: "traffic-engineering", name: "Traffic engineering" },
  { slug: "water-engineering", name: "Water engineering" },
  { slug: "fire-engineering", name: "Fire engineering" },
  { slug: "general-contracting", name: "General contracting" },
  { slug: "facade-systems", name: "Facade systems" },
  { slug: "drywall-plaster", name: "Drywall and plaster" },
  { slug: "masonry", name: "Masonry" },
  { slug: "concrete-works", name: "Concrete works" },
  { slug: "excavation-earthworks", name: "Excavation and earthworks" },
  { slug: "elevators-lifts", name: "Elevators and lifts" },
  { slug: "solar-installation", name: "Solar installation" },
  { slug: "industrial-cleaning", name: "Industrial cleaning" },
  { slug: "grounds-maintenance", name: "Grounds maintenance" },
  { slug: "parking-services", name: "Parking services" },
  { slug: "web-development", name: "Web development" },
  { slug: "mobile-apps", name: "Mobile apps" },
  { slug: "cybersecurity", name: "Cybersecurity" },
  { slug: "cloud-services", name: "Cloud services" },
  { slug: "data-analytics", name: "Data analytics" },
  { slug: "ai-machine-learning", name: "AI and machine learning" },
  { slug: "erp-systems", name: "ERP systems" },
  { slug: "branding", name: "Branding" },
  { slug: "public-relations", name: "Public relations" },
  { slug: "content-marketing", name: "Content marketing" },
  { slug: "seo-sem", name: "SEO and SEM" },
  { slug: "packaging-design", name: "Packaging design" },
  { slug: "management-consulting", name: "Management consulting" },
  { slug: "tax-advisory", name: "Tax advisory" },
  { slug: "audit", name: "Audit" },
  { slug: "hr-consulting", name: "HR consulting" },
  { slug: "compliance", name: "Compliance" },
  { slug: "banking", name: "Banking" },
  { slug: "fintech", name: "Fintech" },
  { slug: "brokerage", name: "Brokerage" },
  { slug: "warehousing", name: "Warehousing" },
  { slug: "courier-express", name: "Courier and express" },
  { slug: "customs-brokerage", name: "Customs brokerage" },
  { slug: "retail", name: "Retail" },
  { slug: "metalworking", name: "Metalworking" },
  { slug: "plastics", name: "Plastics" },
  { slug: "furniture-manufacturing", name: "Furniture manufacturing" },
  { slug: "property-management", name: "Property management" },
  { slug: "property-brokerage", name: "Property brokerage" },
  { slug: "renewable-energy", name: "Renewable energy" },
  { slug: "recycling", name: "Recycling" },
  { slug: "water-treatment", name: "Water treatment" },
  { slug: "medical-devices", name: "Medical devices" },
  { slug: "veterinary", name: "Veterinary" },
  { slug: "pharmacies", name: "Pharmacies" },
  { slug: "restaurants", name: "Restaurants" },
  { slug: "sports-leisure", name: "Sports and leisure" },
  { slug: "public-administration", name: "Public administration" },
  { slug: "ngo-associations", name: "NGOs and associations" },
];
