-- Expand taxonomy for registration browse (groups → subcategories).
-- Existing slugs unchanged; new rows are additive.

insert into public.categories (slug, name) values
  ('quantity-surveying', 'Quantity surveying'),
  ('heritage-conservation', 'Heritage conservation'),
  ('bim-services', 'BIM services'),
  ('geotechnical-engineering', 'Geotechnical engineering'),
  ('acoustic-engineering', 'Acoustic engineering'),
  ('traffic-engineering', 'Traffic engineering'),
  ('water-engineering', 'Water engineering'),
  ('fire-engineering', 'Fire engineering'),
  ('general-contracting', 'General contracting'),
  ('facade-systems', 'Facade systems'),
  ('drywall-plaster', 'Drywall and plaster'),
  ('masonry', 'Masonry'),
  ('concrete-works', 'Concrete works'),
  ('excavation-earthworks', 'Excavation and earthworks'),
  ('elevators-lifts', 'Elevators and lifts'),
  ('solar-installation', 'Solar installation'),
  ('industrial-cleaning', 'Industrial cleaning'),
  ('grounds-maintenance', 'Grounds maintenance'),
  ('parking-services', 'Parking services'),
  ('web-development', 'Web development'),
  ('mobile-apps', 'Mobile apps'),
  ('cybersecurity', 'Cybersecurity'),
  ('cloud-services', 'Cloud services'),
  ('data-analytics', 'Data analytics'),
  ('ai-machine-learning', 'AI and machine learning'),
  ('erp-systems', 'ERP systems'),
  ('branding', 'Branding'),
  ('public-relations', 'Public relations'),
  ('content-marketing', 'Content marketing'),
  ('seo-sem', 'SEO and SEM'),
  ('packaging-design', 'Packaging design'),
  ('management-consulting', 'Management consulting'),
  ('tax-advisory', 'Tax advisory'),
  ('audit', 'Audit'),
  ('hr-consulting', 'HR consulting'),
  ('compliance', 'Compliance'),
  ('banking', 'Banking'),
  ('fintech', 'Fintech'),
  ('brokerage', 'Brokerage'),
  ('warehousing', 'Warehousing'),
  ('courier-express', 'Courier and express'),
  ('customs-brokerage', 'Customs brokerage'),
  ('retail', 'Retail'),
  ('metalworking', 'Metalworking'),
  ('plastics', 'Plastics'),
  ('furniture-manufacturing', 'Furniture manufacturing'),
  ('property-management', 'Property management'),
  ('property-brokerage', 'Property brokerage'),
  ('renewable-energy', 'Renewable energy'),
  ('recycling', 'Recycling'),
  ('water-treatment', 'Water treatment'),
  ('medical-devices', 'Medical devices'),
  ('veterinary', 'Veterinary'),
  ('pharmacies', 'Pharmacies'),
  ('restaurants', 'Restaurants'),
  ('sports-leisure', 'Sports and leisure'),
  ('public-administration', 'Public administration'),
  ('ngo-associations', 'NGOs and associations')
on conflict (slug) do nothing;

insert into public.category_aliases (alias, category_slug)
select lower(name), slug from public.categories
on conflict (alias) do nothing;

insert into public.category_aliases (alias, category_slug) values
  ('quantity surveyor', 'quantity-surveying'),
  ('baukostenplanung', 'quantity-surveying'),
  ('denkmalschutz', 'heritage-conservation'),
  ('bim', 'bim-services'),
  ('geotechnik', 'geotechnical-engineering'),
  ('akustik', 'acoustic-engineering'),
  ('verkehrsplanung', 'traffic-engineering'),
  ('wasserbau', 'water-engineering'),
  ('brandschutzplanung', 'fire-engineering'),
  ('generalunternehmer', 'general-contracting'),
  ('general contractor', 'general-contracting'),
  ('fassade', 'facade-systems'),
  ('trockenbau', 'drywall-plaster'),
  ('maurer', 'masonry'),
  ('zidanje', 'masonry'),
  ('betonbau', 'concrete-works'),
  ('erdbau', 'excavation-earthworks'),
  ('aufzug', 'elevators-lifts'),
  ('liftovi', 'elevators-lifts'),
  ('photovoltaik', 'solar-installation'),
  ('solar installation', 'solar-installation'),
  ('industriereinigung', 'industrial-cleaning'),
  ('gartenpflege', 'grounds-maintenance'),
  ('parkplatz', 'parking-services'),
  ('web development', 'web-development'),
  ('webentwicklung', 'web-development'),
  ('mobile apps', 'mobile-apps'),
  ('cybersicherheit', 'cybersecurity'),
  ('it security', 'cybersecurity'),
  ('cloud', 'cloud-services'),
  ('data analytics', 'data-analytics'),
  ('datenanalyse', 'data-analytics'),
  ('machine learning', 'ai-machine-learning'),
  ('ki', 'ai-machine-learning'),
  ('erp', 'erp-systems'),
  ('markenberatung', 'branding'),
  ('public relations', 'public-relations'),
  ('content marketing', 'content-marketing'),
  ('seo', 'seo-sem'),
  ('sem', 'seo-sem'),
  ('packaging design', 'packaging-design'),
  ('management consulting', 'management-consulting'),
  ('wirtschaftsprufung', 'audit'),
  ('hr consulting', 'hr-consulting'),
  ('hr beratung', 'hr-consulting'),
  ('banking', 'banking'),
  ('bank', 'banking'),
  ('fintech', 'fintech'),
  ('makler', 'brokerage'),
  ('lagerhaltung', 'warehousing'),
  ('skladiste', 'warehousing'),
  ('kurier', 'courier-express'),
  ('zoll', 'customs-brokerage'),
  ('einzelhandel', 'retail'),
  ('maloprodaja', 'retail'),
  ('metallbau', 'metalworking'),
  ('kunststoff', 'plastics'),
  ('mobel', 'furniture-manufacturing'),
  ('property management', 'property-management'),
  ('hausverwaltung', 'property-management'),
  ('immobilienmakler', 'property-brokerage'),
  ('erneuerbare', 'renewable-energy'),
  ('recycling', 'recycling'),
  ('wasseraufbereitung', 'water-treatment'),
  ('medizintechnik', 'medical-devices'),
  ('veterinar', 'veterinary'),
  ('apotheke', 'pharmacies'),
  ('restaurant', 'restaurants'),
  ('sport', 'sports-leisure'),
  ('public administration', 'public-administration'),
  ('verwaltung', 'public-administration'),
  ('ngo', 'ngo-associations'),
  ('verein', 'ngo-associations'),
  ('udruzenje', 'ngo-associations')
on conflict (alias) do nothing;
