-- Expand the ranking taxonomy. Existing slugs stay; new rows are additive.
insert into public.categories (slug, name) values
  ('surveying', 'Surveying'),
  ('carpentry', 'Carpentry'),
  ('insulation', 'Insulation'),
  ('fire-protection', 'Fire protection'),
  ('locksmiths', 'Locksmiths'),
  ('pest-control', 'Pest control'),
  ('catering', 'Catering'),
  ('marketing', 'Marketing'),
  ('media', 'Media'),
  ('notaries', 'Notaries'),
  ('insurance', 'Insurance'),
  ('financial-services', 'Financial services'),
  ('recruitment', 'Recruitment'),
  ('education-training', 'Education and training'),
  ('translation', 'Translation'),
  ('shipping', 'Shipping'),
  ('wholesale', 'Wholesale'),
  ('machinery', 'Machinery'),
  ('electronics', 'Electronics'),
  ('automotive', 'Automotive'),
  ('food-production', 'Food production'),
  ('chemicals', 'Chemicals'),
  ('pharmaceuticals', 'Pharmaceuticals'),
  ('packaging', 'Packaging'),
  ('textiles', 'Textiles'),
  ('environmental-services', 'Environmental services'),
  ('research-laboratories', 'Research and laboratories'),
  ('events', 'Events'),
  ('travel', 'Travel'),
  ('photography-video', 'Photography and video'),
  ('printing', 'Printing'),
  ('agriculture', 'Agriculture'),
  ('call-center', 'Call center')
on conflict (slug) do nothing;

insert into public.category_aliases (alias, category_slug)
select lower(name), slug from public.categories
on conflict (alias) do nothing;

insert into public.category_aliases (alias, category_slug) values
  ('vermessung', 'surveying'),
  ('zimmerei', 'carpentry'),
  ('tischlerei', 'carpentry'),
  ('stolar', 'carpentry'),
  ('daemmung', 'insulation'),
  ('dammung', 'insulation'),
  ('brandschutz', 'fire-protection'),
  ('schluesseldienst', 'locksmiths'),
  ('bravar', 'locksmiths'),
  ('pest control', 'pest-control'),
  ('ketering', 'catering'),
  ('marketingagentur', 'marketing'),
  ('online marketing', 'marketing'),
  ('presse', 'media'),
  ('notar', 'notaries'),
  ('versicherung', 'insurance'),
  ('osiguranje', 'insurance'),
  ('personalberatung', 'recruitment'),
  ('recruiting', 'recruitment'),
  ('zeitarbeit', 'recruitment'),
  ('staffing', 'recruitment'),
  ('weiterbildung', 'education-training'),
  ('schulung', 'education-training'),
  ('obuka', 'education-training'),
  ('uebersetzung', 'translation'),
  ('prevodjenje', 'translation'),
  ('reederei', 'shipping'),
  ('grosshandel', 'wholesale'),
  ('veleprodaja', 'wholesale'),
  ('maschinenbau', 'machinery'),
  ('elektronik', 'electronics'),
  ('automobil', 'automotive'),
  ('kfz', 'automotive'),
  ('lebensmittel', 'food-production'),
  ('chemie', 'chemicals'),
  ('pharma', 'pharmaceuticals'),
  ('verpackung', 'packaging'),
  ('textil', 'textiles'),
  ('umweltschutz', 'environmental-services'),
  ('labor', 'research-laboratories'),
  ('call centre', 'call-center'),
  ('call center', 'call-center'),
  ('callcenter', 'call-center'),
  ('kontakt center', 'call-center'),
  ('bpo', 'call-center'),
  ('landwirtschaft', 'agriculture'),
  ('poljoprivreda', 'agriculture'),
  ('farming', 'agriculture'),
  ('agrar', 'agriculture'),
  ('veranstaltung', 'events'),
  ('eventagentur', 'events'),
  ('reisen', 'travel'),
  ('turizam', 'travel'),
  ('fotografie', 'photography-video'),
  ('druckerei', 'printing'),
  ('stamparija', 'printing')
on conflict (alias) do nothing;

update public.companies c
set category_slug = a.category_slug
from public.category_aliases a
where c.category_slug is null
  and lower(trim(c.category)) = a.alias;
